### ISSUE TITLE
Authentication token can't be parsed if token contains non-latin characters

### ISSUE THREAD

**Issue by antonGritsenko** [abpframework/abp#19763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have project based on ABP EFCore + angular UI that using IdentityServer with internal accounts and OAuth (no 3d party providers). After migration to version 8.1 the entire authentication completely broken.
Angular's config:

```
oAuthConfig: {
    issuer: 'https://localhost:44317',
    redirectUri: baseUrl,
    clientId: 'MyApp_App',
    responseType: 'code',
    scope: 'offline_access MyApp',
    requireHttps: true,
  },
```

Workaround from #18895 implemented. 

See actual behavior.

### Reproduction Steps

1. Migrate to 8.1 with IdentityServer 
2. Implement workaround #18895
3. Start project, press Login in angular app
4. Redirected to login page, log in using username (not matter if you set **Remember me** or not) -> OK
5. Redirected back to angular, all good -> OK
6. Create new role using non-latin character and assign to admin user OR set the surname of the admin user using non-latin character, save it
7. Log out, login again -> OK
8. Refresh the page: **NOK** -> error in the console, app not loaded
9. Remove app cookies and app local storage, refresh the page -> logged off, app working again

### Expected behavior

Token still valid after refresh the page

### Actual behavior

Error in the console:

```
main.ts:12  ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at RememberMeService.getFromToken (http://localhost:4200/vendor.js:25583:36)
    at AuthCodeFlowStrategy.checkRememberMeOption (http://localhost:4200/vendor.js:25718:54)
    at http://localhost:4200/vendor.js:25709:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:4200/vendor.js:139661:24)
    at _next (http://localhost:4200/vendor.js:139680:9)
    at http://localhost:4200/vendor.js:139685:7
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:10356:23)
    at http://localhost:4200/vendor.js:139677:12
    at AuthCodeFlowStrategy.init (http://localhost:4200/vendor.js:25711:7)
```

I did breakpoint on RememberMeService.getFromToken, the token is there and valid, I can decode it using jwt.io (I can share it privately). 

### Regression?

Yes (works in v6, v7)

### Known Workarounds

No

### Version

8.1.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

Other findings:
Based on https://github.com/abpframework/abp/blob/8.1.0/npm/ng-packs/packages/oauth/src/lib/services/remember-me.service.ts
```
atob(accessToken.split('.')[0]) - > OK
atob(accessToken.split('.')[1]) - > ERROR
atob(accessToken.split('.')[2]) - > ERROR
```

**Comment by antonGritsenko** [comment]
Also it will work in 8.0, because it not using the new RememberMeService

**Comment by antonGritsenko** [comment]
@maliming I have found the root cause: if non-latin characters present in the token then it can't be parsed by atob. You must use some other way to decode the token.

**Comment by antonGritsenko** [comment]
https://github.com/fenichelar/ember-simple-auth-token/issues/142

**Comment by antonGritsenko** [comment]
Fix:
```
  getFromToken(accessToken: string) {
    let payload = accessToken.split('.')[1];
    // fix for non-latin
    let safePayload = payload.replace(/-/g, '+').replace(/_/g, '/');
    const parsedToken = JSON.parse(atob(safePayload));
    return Boolean(parsedToken[this.#rememberMe]);
  }
```

**Comment by maliming** [comment]
Thanks @antonGritsenko 

This sounds like an angular issue.

@Sinan997  Can you check this?
