### ISSUE TITLE
NullInjectorError: No provider for ScrollbarHelper!

### ISSUE THREAD

**Issue by numanrauf** [abpframework/abp#5780]
Hi!
After upgrading to 3.2.1 I am getting this error in angular application.
core.js:4352 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(SettingsModule)[ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper]: 
  NullInjectorError: No provider for ScrollbarHelper!
NullInjectorError: R3InjectorError(SettingsModule)[ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper -> ScrollbarHelper]: 
  NullInjectorError: No provider for ScrollbarHelper! 
![Capture](https://user-images.githubusercontent.com/62383069/95838212-2dad3880-0d4a-11eb-8cdf-a490c31067ec.PNG)

**Comment by numanrauf** [comment]
After some fixes, its working now... Thanks
