### ISSUE TITLE
Can not import UiExtensionsModule from @abp/ng.theme.shared/extensions.

### ISSUE THREAD

**Issue by SooRaj-1994** [abpframework/abp#18695]
Ui: Angular

I'm currently in the process of migrating my application from version 5.2.2 to the latest 8.0.0. After replacing some components, the application functions correctly in version 5.2.2. Upon inspecting the node modules of the old application, the extensions folder is clearly visible.

![image](https://github.com/abpframework/abp/assets/74040495/83d9573c-0070-4034-93b6-ead91c7c6ff1)

Upon installing the new version and adding the node modules using yarn (also tried npm), I encountered the following error: "Cannot find module '@abp/ng.theme.shared/extensions' or its corresponding type declarations."

Additionally, I couldn't locate the extensions folder within the ng.theme.shared directory in the node_modules.
![image](https://github.com/abpframework/abp/assets/74040495/257afb5f-2dc2-4839-9750-98e7383a2854)

I've checked your documentation for any module replacement instructions, but I couldn't find any relevant changes. In the provided example, the UiExtensionsModule is imported with '@abp/ng.theme.shared/extensions,' similar to my approach, yet it's not functioning in my case.

**Comment by yinchang0626** [comment]
@SooRaj-1994 
`@abp/ng.component/extensible`
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/components/extensible/src/lib/extensible.module.ts

**Comment by JigneshBuoyancy** [comment]
I am also getting the same error after upgrading to version 8.0.5 from 7.4.0. Can you please let me know what is the solution to overcome this?

Thank you

**Comment by masumulu28** [comment]
Hi, what is exactly your error ? Can you show the error messages ? It must couldn't find the `components | directives | pipes` some of them are convert to `standalone` yet we expose all of it in [ExtensibleModule](https://github.com/abpframework/abp/blob/rel-8.0/npm/ng-packs/packages/components/extensible/src/lib/extensible.module.ts#L50)
