### ISSUE TITLE
Cannot find module 'should-quote' when running `abp generate-proxy` after update to 4.3.0-RC.1

### ISSUE THREAD

**Issue by gregbrant2** [abpframework/abp#8313]
* Your **ABP Framework version**: 4.3.0-RC.1.
* Your **User Interface** type : Angular
* Your database provider(EF Core/MongoDB): EF
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

1. Upgrade a project from 4.2.2 to 4.3.0-RC.1
2. Run the .net API (after fixing some nuget issues related to EFCore 5.0.3/5.0.4)
3. run `abp generate-proxy` and receive the following error:

> > abp generate-proxy
> [10:07:43 INF] ABP CLI (https://abp.io)
> [10:07:43 INF] Version 4.3.0-rc.1 (Prerelease)
> [10:07:44 WRN] Couldn't determinate version of "@abp/ng.schematics" package.
> An unhandled exception occurred: Cannot find module 'should-quote'
> Require stack:
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\models\method.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\models\index.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\utils\type.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\utils\namespace.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\utils\enum.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\utils\index.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@abp\ng.schematics\commands\proxy-add\index.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular-devkit\schematics\tools\export-ref.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular-devkit\schematics\tools\index.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular\cli\utilities\json-schema.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular\cli\models\command-runner.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular\cli\lib\cli\index.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular\cli\lib\init.js
> - C:\Work\excel2000\ExcelErp\angular\node_modules\@angular\cli\bin\ng
> See "C:\Users\greg\AppData\Local\Temp\ng-ra02s5\angular-errors.log" for further details.

I've deleted node_modules and run `yarn` again to fetch the packages fresh and still receive the same error.

**Comment by realLiangshiwei** [comment]
May related to https://github.com/abpframework/abp/issues/8311
